project:
  type: default
  output-dir: _assign

format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    code-tools: true
    highlight-style: pygments
    html-math-method: mathjax
